name: mad_cw6
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase dependencies with specific versions
  firebase_core: ^1.24.0         # Firebase Core SDK for Flutter
  firebase_auth: ^3.3.16         # Firebase Authentication
  cloud_firestore: ^3.1.18       # Firestore database

dependency_overrides:
  firebase_core_platform_interface: ^4.0.0
  firebase_auth_platform_interface: ^6.0.0
  firebase_auth_web: ^4.0.1
  cloud_firestore_platform_interface: ^5.0.0
  cloud_firestore_web: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
